apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "praetor.fullname" . }}-controller
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "praetor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "praetor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "praetor.fullname" . }}-controller
      containers:
        - name: controller
          image: "praetor-controller:latest"
          imagePullPolicy: Never
          env:
            - name: NATS_URL
              value: "nats://{{ include "praetor.fullname" . }}-nats:4222"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "praetor.fullname" . }}-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "praetor.fullname" . }}-controller
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["create", "get", "context", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "praetor.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "praetor.fullname" . }}-controller
roleRef:
  kind: Role
  name: {{ include "praetor.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
