apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "praetor.fullname" . }}-executor
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: executor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "praetor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: executor
  template:
    metadata:
      labels:
        {{- include "praetor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: executor
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "praetor.fullname" . }}-nats 4222; do echo waiting for nats; sleep 2; done;']
      containers:
        - name: executor
          image: "praetor-executor:latest"
          imagePullPolicy: Never
          env:
            - name: NATS_URL
              value: "nats://{{ include "praetor.fullname" . }}-nats:4222"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
