apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "praetor.fullname" . }}-migrator
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrator
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "praetor.fullname" . }}-migrator
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ include "praetor.fullname" . }}-db 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: migrator
          image: "praetor-migrator:latest"
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "praetor.fullname" . }}-db:5432/{{ .Values.postgres.db }}?sslmode=disable"
