apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "praetor.fullname" . }}-nats
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "praetor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nats
  template:
    metadata:
      labels:
        {{- include "praetor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: nats
              containerPort: 4222
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "praetor.fullname" . }}-nats
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nats.service.port }}
      targetPort: nats
      protocol: TCP
      name: nats
  selector:
    {{- include "praetor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats
