apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "praetor.fullname" . }}-db
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "praetor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        {{- include "praetor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.db }}"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "praetor.fullname" . }}-db
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "praetor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
