apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "praetor.fullname" . }}-ui
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "praetor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "praetor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      containers:
        - name: ui
          image: "praetor-ui:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "praetor.fullname" . }}-ui
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
spec:
  type: NodePort # Or LoadBalancer / Ingress
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      nodePort: 30080
  selector:
    {{- include "praetor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
